/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package swagger.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.swagger.Implicits._
case class MarketSubscriptionMessage(id: Option[Int] = None, segmentationEnabled: Option[Boolean] = None, clk: Option[String] = None, heartbeatMs: Option[Long] = None, initialClk: Option[String] = None, marketFilter: Option[MarketFilter] = None, conflateMs: Option[Long] = None, marketDataFilter: Option[MarketDataFilter] = None) extends RequestMessage
object MarketSubscriptionMessage {
  implicit val encodeMarketSubscriptionMessage: _root_.io.circe.Encoder.AsObject[MarketSubscriptionMessage] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[MarketSubscriptionMessage](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("id", a.id.asJson), ("segmentationEnabled", a.segmentationEnabled.asJson), ("clk", a.clk.asJson), ("heartbeatMs", a.heartbeatMs.asJson), ("initialClk", a.initialClk.asJson), ("marketFilter", a.marketFilter.asJson), ("conflateMs", a.conflateMs.asJson), ("marketDataFilter", a.marketDataFilter.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeMarketSubscriptionMessage: _root_.io.circe.Decoder[MarketSubscriptionMessage] = new _root_.io.circe.Decoder[MarketSubscriptionMessage] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[MarketSubscriptionMessage] = for (v0 <- c.downField("id").as[Option[Int]]; v1 <- c.downField("segmentationEnabled").as[Option[Boolean]]; v2 <- c.downField("clk").as[Option[String]]; v3 <- c.downField("heartbeatMs").as[Option[Long]]; v4 <- c.downField("initialClk").as[Option[String]]; v5 <- c.downField("marketFilter").as[Option[MarketFilter]]; v6 <- c.downField("conflateMs").as[Option[Long]]; v7 <- c.downField("marketDataFilter").as[Option[MarketDataFilter]]) yield MarketSubscriptionMessage(v0, v1, v2, v3, v4, v5, v6, v7) }
}